### PR TITLE
stream output should be gotten before writers are disposed

### PR DESCRIPTION
**Pull request by smitcham**
I've checked my local commits to ensure that they have the right email on the commit.

### CODE REVIEW

**Comment by smitcham** [comment]
looks like it has the right email this time.

**Comment by jeffrymorris** [comment]
@smitcham - yeah, email looks right, but I don't see the commit yet in Gerrit. Try doing this:

1. Login to Gerrit
2. Click your Avatar on the upper right and then "Settings"
3. Select "Email Addresses" on the menu to your left and then add a new email using the "New Email Address" Textbox and click "Save"

Once you do this in Gerrit, it should come through.

-Jeff

**Comment by smitcham** [comment]
updated. commenting to see if that triggers things.

**Comment by smitcham** [comment]
review was created but isn't pointing to release27

**Comment by brantburnett** [comment]
@smitcham Can I recommend one tweak to this? One of the advantages of disposing the StreamWriter before calling ToArray is that ensures that the writer and encoder are fully flushed to the stream: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs#L190. Instead of calling ToArray() before disposing, I'd recommend using the constructor overload on StreamWriter to pass `leaveOpen` as `true`. This way the dispose won't also dispose the underlying Stream, but the flush still occurs.

**Comment by jeffrymorris** [comment]
@smitcham - SDKBOT pushes to the master branch on Gerrit by default. I pushed to release27 and abandoned the commit on master.  Since your now setup on Gerrit, I suggest you just push to Gerrit directly from now on - just add Gerrit as a remote (`git remote add gerrit ssh://[your username]@review.couchbase.org:29418/couchbase-net-client.git ` . Note on Gerrit, the workflow is:

1. `git add .`
2. `git commit --amend`
3. `git push gerrit HEAD:refs/for/release27`

@brantburnett can you add your comment ^ to the review on gerrit?

**Pull request closed without merging**
