### PR TITLE
Update of dependency on Common.Logging and Log4Net.

### PR DESCRIPTION
**Pull request by sallgeud**
Also updated the .gitignore file to properly ignore packages, and not ignore the packages.conf files when using visual studio's git integration.

### CODE REVIEW

**Comment by jeffrymorris** [comment]
@sallgeud -

Thanks for the pull request!! To ensure quality review, Couchbase employs a code review system based on Gerrit to manage the workflow of changes in addition to tracking our contributor agreements.

To get this change in and collaborate in code review, please register on Gerrit and accept our CLA. More detailed instructions are available here: http://developer.couchbase.com/open-source-projects#how-to-contribute-code.

This will be part of 2.2.5 which we are shipping the first week of Feb if we can get through CR this week.

Thanks,

Jeff

**Comment by jeffrymorris** [comment]
@sallgeud -

The review is here: http://review.couchbase.org/#/c/59283/

ATM, its -1 for a couple of reasons (see comments for specifics):

- White space issues

- Fails unit tests because the log4net version has changed from 1.2.12.0 to 1.2.15.0 so the binding redirects fail for the unit tests

I can fix both and push a patchset or you can do it as well (you'll still be the author). LMK what you want me to do.

-Jeff

**Comment by sallgeud** [comment]
Go for it.

**Comment by jeffrymorris** [comment]
This is merged, can you please close the PR?

**Pull request closed without merging**
