### PR TITLE
Fix ConfigureAwait(false) not being used to resume without current co…

### PR DESCRIPTION
**Pull request by millerhederi**
…ntext on awaits

### CODE REVIEW

**Comment by millerhederi** [comment]
Creating a sample MVC app that syncronously blocks on the Async method will produce a deadlock with the current implementation.

```csharp
public ActionResult Load()
{
    UpsertAsync().GetAwaiter().GetResult();

    return Content("Loaded!");
}

private static async Task<IDocumentResult<string>>  UpsertAsync()
{
    return await Bucket.Value.UpsertAsync(new Document<string> { Id = "1", Content = "Content" }).ConfigureAwait(false);
}
```

**Comment by jeffrymorris** [comment]
@millerhederi -

Thanks for the submission! If you haven't already done so, would you mind creating a Gerrit (our code review system: review.couchbase.com) account and signing the CLA? Here are the steps: http://www.couchbase.com/wiki/display/couchbase/Contributing+Changes

Once you do that, I'll push this PR to Gerrit for review and it will be included in 2.2.0 next month assuming it is +2!

Thanks,

Jeff

**Comment by millerhederi** [comment]
@jeffrymorris - 

Hey Jeff, I went ahead and created an account on Gerrit and signed the CLA, hopefully should be good to go.

**Comment by millerhederi** [comment]
@jeffrymorris - Is there any update on this? I have not received any notification that the PR has been pushed into Gerrit.

**Comment by jeffrymorris** [comment]
@millerhederi  -

I pushed it the PR to gerrit; there is a backlog of things to be reviewed and merged in gerrit, so it will take a bit of time before it's reviewed. The planned release date for 2.2.0 (the next release) is early October 2015.

-Jeff

**Pull request closed without merging**
