### PR TITLE
Add double lock check in connection pool acquire

### PR DESCRIPTION
**Pull request by dmytro-storozhuk**
During load testing I noticed several time intervals where client stops to send requests to the server, after adding additional logs was discovered that if client activity increases dramatically and you don't have enough connections in the pool all current requests will wait in lock and will try to open new connection one by one. Opening new socket connection takes time and almost for sure that some connections will be released while operation waits in lock. The fix is simple check if connection was released before opening new one.

Pool request also contains unit test which covers such case.

### CODE REVIEW

**Comment by jeffrymorris** [comment]
@dmytro-storozhuk 

Thanks for the pull request!! To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org) based on Gerrit to manage the workflow of changes in addition to tracking our contributor agreements.

To get this change in and collaborate in code review, please register on Gerrit and accept our CLA. More detailed instructions are available here: http://developer.couchbase.com/open-source-projects#how-to-contribute-code.

Thanks,

Jeff

**Comment by dmytro-storozhuk** [comment]
Hi @jeffrymorris,

I've registered and signed agreement with my Yahoo account dmytro.storozhuk@yahoo.com

BR,
Dmytro

**Comment by jeffrymorris** [comment]
@dmytro-storozhuk -

In your profile on Gerrit, can you add your email? Gerrit requires it for me to push your PR or else it will reject it.

Thanks!

-Jeff

**Comment by ingenthr** [comment]
I got this up on review, it seemed to be missing a change-id:
http://review.couchbase.org/#/c/58347/

**Comment by dmytro-storozhuk** [comment]
@jeffrymorris 

I registered preferred email in settings but my profile hasn't been changed.
My Gerrit account ID is 1003726.

Dmytro

**Comment by jeffrymorris** [comment]
@dmytro-storozhuk -

This has been merged w/master, can you please close this PR?

Thanks!

Jeff

**Pull request closed without merging**
