### PR TITLE
Make NuGet.exe Executable

### PR DESCRIPTION
**Pull request by iwillspeak**
Updates the attributes on NuGet to make it executable. This is useful if the repo is cloned under Cygwin.

### CODE REVIEW

**Comment by brett19** [comment]
Thanks for the pull request!!  To ensure quality review, Couchbase employs a [code review system](http://review.couchbase.org/) based on [Gerrit](https://www.gerritcodereview.com/) to manage the workflow of changes in addition to tracking our contributor agreements.

To get this change in and collaborate in code review, please register on Gerrit and accept our CLA.  More detailed instructions are available here: http://developer.couchbase.com/open-source-projects#how-to-contribute-code.

Note: Please contact us if you have any issues registering with Gerrit!  If you are not registered after 7 days, the Pull Request will automatically be closed.

::SDKBOT/PR:no_cla

**Comment by jeffrymorris** [comment]
@iwillspeak -

Thanks for the submission.

-Jeff

**Comment by jeffrymorris** [comment]
@iwillspeak -

Can you sign the CLA? I can't merge this without it being signed.

Thanks!

-Jeff

**Comment by brett19** [comment]
Unfortunately it has been 7 days and we are still unable to confirm that you have signed our CLA.  We sincerely appreciate your submission and hope that you will register and resubmit this Pull Request in the future!

::SDKBOT/PR:timeout

**Comment by iwillspeak** [comment]
I'm currently waiting on my employer to confirm that we can release this code and other contributions I make at work. Fingers crossed it shouldn't take too long.

**Comment by jeffrymorris** [comment]
@iwillspeak -

Awesome! Will keep this open then.

-Jeff

**Comment by jeffrymorris** [comment]
@iwillspeak -

Any progress here?

-Jeff

**Comment by iwillspeak** [comment]
Hi, sorry for the delay. I've signed the CLA now.

**Comment by jeffrymorris** [comment]
@iwillspeak -

This has been merged with master, can you please close this PR?

Thanks for the contribution!

-Jeff

**Comment by iwillspeak** [comment]
:+1: Thanks. :rocket:

**Pull request closed without merging**
