### PR TITLE
Fix debug message format

### PR DESCRIPTION
**Pull request by frasdav**
Fixes the following issue when connecting to a Couchbase 6.6.0 cluster using TLS.

```
[2021-01-20 21:59:42,196] [Warning] [Login] [Couchbase.Configuration.Server.Providers.ConfigProviderBase] System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Common.Logging.Factory.AbstractLogger.StringFormatFormattedMessage.ToString() in C:\_oss\common-logging\src\Common.Logging.Portable\Logging\Factory\AbstractLogger.cs:line 164
   at Common.Logging.EntLib.EntLibLogger.PopulateLogEntry(LogEntry log, Object message, Exception ex) in c:\_oss\common-logging\src\Common.Logging.EntLib60\Logging\EntLib\EntLibLogger.cs:line 243
   at Common.Logging.EntLib.EntLibLogger.WriteInternal(LogLevel logLevel, Object message, Exception exception) in c:\_oss\common-logging\src\Common.Logging.EntLib60\Logging\EntLib\EntLibLogger.cs:line 170
   at Common.Logging.Factory.AbstractLogger.DebugFormat(String format, Object[] args) in C:\_oss\common-logging\src\Common.Logging.Portable\Logging\Factory\AbstractLogger.cs:line 467
   at Couchbase.Logging.CommonLoggingLogger.Debug(String format, Object[] args) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\Logging\CommonLoggingLogger.cs:line 34
   at Couchbase.IO.ConnectionPoolBase`1.EnableEnhancedAuthentication(IConnection connection) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\IO\ConnectionPoolBase.cs:line 177
   at Couchbase.IO.ConnectionPool`1.Acquire() in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\IO\ConnectionPool.cs:line 124
   at Couchbase.IO.Services.PooledIOService.Execute[T](IOperation`1 operation) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\IO\Services\PooledIOService.cs:line 130
   at Couchbase.Configuration.Server.Providers.CarrierPublication.CarrierPublicationProvider.GetConfig(String bucketName, String username, String password) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\Configuration\Server\Providers\CarrierPublication\CarrierPublicationProvider.cs:line 72
[2021-01-20 21:59:42,202] [Warning] [Login] [Couchbase.Core.ClusterController] System.AggregateException: Could not bootstrap with CCCP. ---> System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Common.Logging.Factory.AbstractLogger.StringFormatFormattedMessage.ToString() in C:\_oss\common-logging\src\Common.Logging.Portable\Logging\Factory\AbstractLogger.cs:line 164
   at Common.Logging.EntLib.EntLibLogger.PopulateLogEntry(LogEntry log, Object message, Exception ex) in c:\_oss\common-logging\src\Common.Logging.EntLib60\Logging\EntLib\EntLibLogger.cs:line 243
   at Common.Logging.EntLib.EntLibLogger.WriteInternal(LogLevel logLevel, Object message, Exception exception) in c:\_oss\common-logging\src\Common.Logging.EntLib60\Logging\EntLib\EntLibLogger.cs:line 170
   at Common.Logging.Factory.AbstractLogger.DebugFormat(String format, Object[] args) in C:\_oss\common-logging\src\Common.Logging.Portable\Logging\Factory\AbstractLogger.cs:line 467
   at Couchbase.Logging.CommonLoggingLogger.Debug(String format, Object[] args) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\Logging\CommonLoggingLogger.cs:line 34
   at Couchbase.IO.ConnectionPoolBase`1.EnableEnhancedAuthentication(IConnection connection) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\IO\ConnectionPoolBase.cs:line 177
   at Couchbase.IO.ConnectionPool`1.Acquire() in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\IO\ConnectionPool.cs:line 124
   at Couchbase.IO.Services.PooledIOService.Execute[T](IOperation`1 operation) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\IO\Services\PooledIOService.cs:line 130
   at Couchbase.Configuration.Server.Providers.CarrierPublication.CarrierPublicationProvider.GetConfig(String bucketName, String username, String password) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\Configuration\Server\Providers\CarrierPublication\CarrierPublicationProvider.cs:line 72
   --- End of inner exception stack trace ---
   at Couchbase.Configuration.Server.Providers.CarrierPublication.CarrierPublicationProvider.GetConfig(String bucketName, String username, String password) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\Configuration\Server\Providers\CarrierPublication\CarrierPublicationProvider.cs:line 166
   at Couchbase.Core.ClusterController.CreateBucketImpl(String bucketName, String password, IAuthenticator authenticator) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\Core\ClusterController.cs:line 325
---> (Inner Exception #0) System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Common.Logging.Factory.AbstractLogger.StringFormatFormattedMessage.ToString() in C:\_oss\common-logging\src\Common.Logging.Portable\Logging\Factory\AbstractLogger.cs:line 164
   at Common.Logging.EntLib.EntLibLogger.PopulateLogEntry(LogEntry log, Object message, Exception ex) in c:\_oss\common-logging\src\Common.Logging.EntLib60\Logging\EntLib\EntLibLogger.cs:line 243
   at Common.Logging.EntLib.EntLibLogger.WriteInternal(LogLevel logLevel, Object message, Exception exception) in c:\_oss\common-logging\src\Common.Logging.EntLib60\Logging\EntLib\EntLibLogger.cs:line 170
   at Common.Logging.Factory.AbstractLogger.DebugFormat(String format, Object[] args) in C:\_oss\common-logging\src\Common.Logging.Portable\Logging\Factory\AbstractLogger.cs:line 467
   at Couchbase.Logging.CommonLoggingLogger.Debug(String format, Object[] args) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\Logging\CommonLoggingLogger.cs:line 34
   at Couchbase.IO.ConnectionPoolBase`1.EnableEnhancedAuthentication(IConnection connection) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\IO\ConnectionPoolBase.cs:line 177
   at Couchbase.IO.ConnectionPool`1.Acquire() in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\IO\ConnectionPool.cs:line 124
   at Couchbase.IO.Services.PooledIOService.Execute[T](IOperation`1 operation) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\IO\Services\PooledIOService.cs:line 130
   at Couchbase.Configuration.Server.Providers.CarrierPublication.CarrierPublicationProvider.GetConfig(String bucketName, String username, String password) in C:\Users\frasd\Code\couchbase-net-client\Src\Couchbase\Configuration\Server\Providers\CarrierPublication\CarrierPublicationProvider.cs:line 72<---
```

### CODE REVIEW

**Comment by jeffrymorris** [comment]
@frasdav  - can you sign the SLA?  http://review.couchbase.org/#/settings/new-agreement

**Comment by frasdav** [comment]
@jeffrymorris Already have done, I did it when I submitted the PR.
Screenshot 2021-02-08 at 17 52 19

**Comment by jeffrymorris** [comment]
@frasdav -

Thanks! Can you verify the email you used in the github commit matches the gerrit email? You may need to add the one used in the github commit to gerrit. I cannot find this commit in gerrit as of today.

-Jeff

**Comment by jeffrymorris** [comment]
@frasdav -

Just following up here, would love to get this through CR and merged but can't locate it in gerrit. You might want to check the email used in the github account of the initial commit and add it to gerrit if its missing. http://review.couchbase.org/settings/#EmailAddresses

-Jeff

**Comment by brett19** [comment]
Hey @fasdave,

I just took a look and saw that your email (f****r@fdav*****.com) still hasn't been linked to your Gerrit account so that we can link the pull-request up to you in Gerrit.  We would really like to see this merged, let us know if you're having any trouble!  As @jeffrymorris mentioned, you can easily add emails to Gerrit here: http://review.couchbase.org/settings/#EmailAddresses

Chers, Brett

**Pull request closed without merging**
