### PR TITLE
CouchbaseBucket holds its own non-configurable ITypeTranscoder with a DefaultSerializer

### PR DESCRIPTION
**Pull request by yellowblood**
When using a custom `ITypeSerializer`, for example in order to add a custom JSON converter, it may not be used by certain methods of `CouchbaseBucket`, like `GetAsync<T>(key)` .

So, while the method `QueryAsync<T>(queryRequest)` ends up using the correct, configured ITypeSerializer, this is ignored by the method `GetAsync<T>(key)`.

In my codebase I horribly solved this with reflection after every creation of a bucket instance:
```
                                var bucket = _cluster.OpenBucket(bucketName);
				var transcoder = bucket.GetType().GetField("_transcoder", BindingFlags.NonPublic | BindingFlags.Instance)?.GetValue(bucket);
				var serializer = (DefaultSerializer)((DefaultTranscoder)transcoder).Serializer;
				serializer.DeserializationSettings.Converters.Add(new SerializableAbstractTypeConverter());
```

### CODE REVIEW

**Comment by jeffrymorris** [comment]
@yellowblood -

I think you intended to create an issue and not a pull request? You can create issues here: https://issues.couchbase.com/projects/NCBC/summary

Thanks,

Jeff

**Comment by yellowblood** [comment]
Yes, an issue, but I don't have an account in your JIRA. Can you please copy my original post to a JIRA issue?

**Comment by jeffrymorris** [comment]
https://issues.couchbase.com/browse/NCBC-1138

**Comment by yellowblood** [comment]
Thanks!

**Pull request closed without merging**
