### PR TITLE
[WIP] CoreCLR port

### PR DESCRIPTION
**Pull request by antonmes**
I was interested in running on coreclr, so i didn't use #if statements. Hope this helps.
Do you have plans to support CoreCLR?

### CODE REVIEW

**Comment by Strifex** [comment]
This would be incredibly useful if this library can become compatible with .NET Core, I'm working on an ASP.NET 5 project atm and would like to use this library, but unfortunately it will only target standard .NET Framework atm :(

**Comment by jeffrymorris** [comment]
@antonmes -

Thanks for the contribution! Yes, we plan on supporting CoreCLR...we were going to create a separate branch for CoreCLR so that there are no conflicts for users targeting older CLR versions. 

You kind of beat me to the punch here, I was planning on branching after 2.2.3 which is planned for the first week of January. Perhaps you could rebase this on top of the core-clr branch once we get one in place? 

Sorry I didn't respond sooner, I have been on (partial) medical leave for the last couple of weeks.

-Thanks

Jeff

**Comment by ingenthr** [comment]
Hey @antonmes, Jeff and I just talked about how to handle this.  This is definitely something we want to work on!  We think we'll need some more work before the merge to master though, so for now what we're going to do is create a feature branch where we work on updates/rebasing/etc.  It'll probably be January before we get into serious work, but wanted to let you know what's happening.  

Thanks!

**Comment by ingenthr** [comment]
Merged to new branch feature/CoreCLR, where we'll work on this for merging into master.

**Comment by antonmes** [comment]
@jeffrymorris, @ingenthr sorry, I didn't mean merging into master, just wanted to share some thoughts and save some time ;) thanks for answering! I can close this PR, right?

**Comment by jeffrymorris** [comment]
@antonmes no problem, go ahead and close it. We'll use the feature branch for reference and probably create a new one after 2.2.3 is released for core clr.

Thanks, 

Jeff

**Comment by antonmes** [comment]
Hey guys, you can delete feature/CoreCLR if you wish. Thanks!

**Pull request closed without merging**
