### PR TITLE
Implemented AnalyticsIndexManager and Tests

### PR DESCRIPTION
**Pull request by malscent**
Implemented AnalyticsIndexManager and Tests

Added IndexManager to DI registration

### CODE REVIEW

**Comment by malscent** [comment]
CLA submitted.

**Comment by jeffrymorris** [comment]
@malscent -

Thanks for the submission! I don't yet see the commit in Gerrit. I see you submitted the CLA, can you check and see if you registered the same email that you used to push this commit to github?

Thanks,

Jeff

**Comment by malscent** [comment]
Hmm.. I registered with my Github Account and updated my email in Gerrit.  Not sure?

**Comment by jeffrymorris** [comment]
@malscent -

Great, looks like it was pushed to gerrit! Can you add myself and Matt Ingenthron as reviewers? That will make the changeset appear in our incoming reviews queue.

-Jeff

**Comment by malscent** [comment]
Added!

**Comment by jeffrymorris** [comment]
Congrats, this is merged! Thanks again for contributing.

**Pull request closed without merging**
